pipeline:

  publish:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/som-laneweb/eresources
    tag:
      - latest
      - "${DRONE_COMMIT_SHA}"
    secrets: [ docker_username, docker_password ]
    when:
      status: success
      branch: master

  tag-test:
    image: gcr.io/clever-circlet-125504/gcloud
    pull: true
    commands:
      - source gcp-env.sh
      - source env.sh
      - export IMAGE_TAG=$(git describe --abbrev=0)
      - export IMAGE_PATH="${DOCKER_REGISTRY}/${GCP_PROJECT_ID}/${DOCKER_IMAGE}"
      - gcloud --quiet container images add-tag ${IMAGE_PATH}:latest ${IMAGE_PATH}:${IMAGE_TAG}
    secrets: [ gcp_key ]
    when:
      event: tag

  downstream:
    image: plugins/downstream
    server: https://ci.med.stanford.edu
    repositories:
      - irt-lane/kube-eresources
    fork: true
    secrets: [ downstream_token ]
    when:
      status: success
      branch: master

  slack:
    image: plugins/slack
    channel: irt-dcs-cicd
    username: lane/eresources-database
    template: >
      lane/eresources-database build #{{ build.number }} finished with a {{ build.status }} status
      Build log: https://ci.med.stanford.edu/lane/eresources-database/{{ build.number }}
      Changes: https://gitlab.med.stanford.edu/lane/eresources-database/commit/{{ build.commit }}
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      branch: master
