pipeline:

  build:
    image: maven:3-jdk-8-alpine
    volumes:
    - name: maven-cache
      path: /root/.m2/repository
    commands:
        - mvn -B -s settings.xml package
    when:
      branch: master

  publish:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/som-laneweb/eresources
    tag:
      - latest
      - "${DRONE_COMMIT_SHA}"
    secrets: [ docker_username, docker_password ]
    when:
      status: success
      branch: master

  downstream:
    image: plugins/downstream
    server: https://ci.med.stanford.edu
    repositories:
      - irt-lane/kube-eresources
    fork: true
    secrets: [ downstream_token ]
    when:
      status: success
      branch: master

  slack:
    image: plugins/slack
    channel: irt-dcs-cicd
    username: lane/eresources-database
    template: >
      lane/eresources-database build #{{ build.number }} finished with a {{ build.status }} status
      Build log: https://ci.med.stanford.edu/lane/eresources-database/{{ build.number }}
      Changes: https://gitlab.med.stanford.edu/lane/eresources-database/commit/{{ build.commit }}
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      branch: master

volumes:
- name: maven-cache
  host:
    path: /tmp/maven-cache