include:
  - project: "irt-lane/som-laneweb"
    file: "/cicd/build-maven-image.yml"
  - project: "irt-lane/som-laneweb"
    file: "/cicd/trigger-downstream.yml"

snyk-scan:
  stage: code-analysis
  image: maven:latest
  script:
    - mkdir -p .mvn && echo "-s $PWD/settings.xml" >> .mvn/maven.config
    - cat .mvn/maven.config
    - DEBUG=*snyk* mvn -e -B -s settings.xml snyk:test
  cache:
    key: mavenrepo
    paths:
      - ./.m2/repository
  allow_failure: true
  tags:
    - prod-services
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  IMAGE_NAME: "eresources"
  KANIKO_CACHE: "true"

downstream:
  trigger: irt-lane/kube-eresources