include:
  - project: "irt-lane/som-laneweb"
    file: "/cicd/build-image.yml"

variables:
  IMAGE_NAME: "eresources"
  KANIKO_CACHE: "true"

deploy-to-stage:
  stage: deploy
  variables:
    ENVIRONMENT: stage
  trigger: 
    project: irt-lane/kube-eresources
    branch: main